apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: kuber
        image: marina1327/app1-go:dev-2023-11-09-15-26-51
        ports:
        - containerPort: 8080
